import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const bricolageSans = Bricolage_Grotesque({
  subsets: ["latin"],
  display: "swap",
});

const bricolageMono = Bricolage_Grotesque({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Sahrdaya Placement Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bricolageSans.className} ${bricolageMono.className} antialiased`}
      >
        {children}
        <Toaster
          toastOptions={{
            classNames: {
              description: "!text-gray-500",
            },
          }}
        />
      </body>
    </html>
  );
}
